# Generated by Django 5.2.7 on 2025-10-30 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono chileno válido. Ejemplo: +56 912345678 o 912345678', regex='^(\\+56\\s?)?9\\d{8}$')]),
        ),
    ]
